{
    "application": False,
    "author": "Marc Wimmer (marc@zebroo.de)",
    "auto_install": True,
    "conflicts": [],
    "css": [],
    "data": [],
    "demo_xml": [],
    "depends": ["base"],
    "installable": True,
    "js": [],
    "name": "cleardb",
    "qweb": [],
    "test": [],
    "version": "1.0",
}
